<?xml version="1.0" encoding="utf-8"?><Database Name="QLNV" Class="QLNhanVienDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=CANH-DHQN\SQLEXPRESS;Initial Catalog=QLNV;Integrated Security=True" SettingsObjectName="QLNS.Properties.Settings" SettingsPropertyName="QLNVConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="MaNV" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SoDT" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="MaPB" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Picture" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="PHONGBAN_NHANVIEN" Member="PHONGBAN" ThisKey="MaPB" OtherKey="MaPB" Type="PHONGBAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHONGBAN" Member="PHONGBANs">
    <Type Name="PHONGBAN">
      <Column Name="MaPB" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenPB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="PHONGBAN_NHANVIEN" Member="NHANVIENs" ThisKey="MaPB" OtherKey="MaPB" Type="NHANVIEN" />
    </Type>
  </Table>
</Database>